# Generated by Django 3.1.4 on 2020-12-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='chapters',
            new_name='chapter',
        ),
    ]
