# Generated by Django 3.1.4 on 2020-12-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201217_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='exercises',
            new_name='exercise',
        ),
    ]
