# Generated by Django 3.1.4 on 2020-12-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201218_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
